/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2020-06-03 05:42:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.room;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reserve.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<link rel='stylesheet'\r\n");
      out.write("\thref='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css' />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc='//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js'></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"fonts/material-design-iconic-font/css/material-design-iconic-font.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\tfont-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".header-nav-wrapper {\r\n");
      out.write("\tbackground: url(../images/bg_header.gif) repeat-x 0 0;\r\n");
      out.write("\tbackground-position: center;\r\n");
      out.write("\tbackground-size: contain;\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("\tpadding-top: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-nav-container {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\tpadding-left: 40px;\r\n");
      out.write("\tpadding-right: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-inner {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-inner>div {\r\n");
      out.write("\tborder-right: 1px solid #DDDDDD;\r\n");
      out.write("\tmargin-left: 8px;\r\n");
      out.write("\tpadding-right: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-line {\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("\tborder-radius: 50px;\r\n");
      out.write("\theight: 5px;\r\n");
      out.write("  background-position: bottom;\r\n");
      out.write("  background-size: 15px 1px;\r\n");
      out.write("  background-repeat: repeat-x; \r\n");
      out.write("}\r\n");
      out.write(".nav-wrapper {\r\n");
      out.write("\t background: url(../images/bg_header.gif) repeat-x 0 0; \r\n");
      out.write("\t width: 100%;\r\n");
      out.write("\theight: 94px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-content {\r\n");
      out.write("\tpadding-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroomLogo-wrapper {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-inner {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tmargin-left: 150px;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tpadding-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-inner>div>button {\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-wrapper {\r\n");
      out.write("\tmargin-left: 70px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-wrapper>input {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".searchButton {\r\n");
      out.write("\tmargin: 0 !important;\r\n");
      out.write("\tpadding: 2px !important;\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfont-size: 10px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".reserve-container {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\theight: 800px;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserve-container>div {\r\n");
      out.write("\tborder: 1px solid #dddddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserve-title {\r\n");
      out.write("\tborder-bottom: 1px solid #dddddd;\r\n");
      out.write("\tbackground-color: #444444;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: #dddddd;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroom-part {\r\n");
      out.write("\twidth: 284px;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tleft:300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroom-option {\r\n");
      out.write("\twidth: 264px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".day-part {\r\n");
      out.write("\twidth: 91px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".time-part {\r\n");
      out.write("\twidth: 384px;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tleft: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort-wrapper {\r\n");
      out.write("\tmargin: 10px 6px 6px 10px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tborder-bottom: 1px solid #dddddd;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort-wrapper>div {\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort-wrapper>div:hover {\r\n");
      out.write("\tborder-bottom: 1px solid #111111;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort-selected {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tborder-bottom: 1px solid #111111;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort-korean {\r\n");
      out.write("\tmargin-left: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reserve-date {\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\theight: 770px;\r\n");
      out.write("\toverflow: scroll;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroom-date-wrapper {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tpadding: 5px 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroom-week-of-day {\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("\twidth: 12px;\r\n");
      out.write("\theight: 22px;\r\n");
      out.write("\tline-height: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroom-day {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 34px;\r\n");
      out.write("\theight: 22px;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".saturday {\r\n");
      out.write("\tcolor: #31597E;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sunday {\r\n");
      out.write("\tcolor: #AF2D2D;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroom-date-wrapper-active {\r\n");
      out.write("\tbackground-color: #333333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".studyroom-date-wrapper-active>* {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".css_test {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("} \r\n");
      out.write(".mini-calendar{\r\n");
      out.write("position: relative;\r\n");
      out.write("left: 800px;\r\n");
      out.write("width: 900px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".reserve-container{\r\n");
      out.write("width:600px;\r\n");
      out.write("position: relative;\r\n");
      out.write("left: 700px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#calendar{\r\n");
      out.write("background-color:black;\r\n");
      out.write("color:white;\r\n");
      out.write("text-align:center;\r\n");
      out.write("width: 400px;\r\n");
      out.write("height: 200px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-family: 굴림;\r\n");
      out.write("\tborder: 2px border-color:#020202;\r\n");
      out.write("\tborder-radius: 8px; /*모서리 둥글게*/\r\n");
      out.write("}\r\n");
      out.write(".button {\r\n");
      out.write("\r\n");
      out.write("background: transparent;\r\n");
      out.write("border: none;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");

	String context = request.getContextPath();
    System.out.println("context->"+context);

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   \r\n");
      out.write("\tvar today = new Date();//오늘 날짜//내 컴퓨터 로컬을 기준으로 today에 Date 객체를 넣어줌\r\n");
      out.write("\tvar date = new Date();//today의 Date를 세어주는 역할\r\n");
      out.write("\tfunction prevCalendar() {//이전 달\r\n");
      out.write("\t\t// 이전 달을 today에 값을 저장하고 달력에 today를 넣어줌\r\n");
      out.write("\t\t//today.getFullYear() 현재 년도//today.getMonth() 월  //today.getDate() 일 \r\n");
      out.write("\t\t//getMonth()는 현재 달을 받아 오므로 이전달을 출력하려면 -1을 해줘야함\r\n");
      out.write("\t\ttoday = new Date(today.getFullYear(), today.getMonth() - 1, today\r\n");
      out.write("\t\t\t\t.getDate());\r\n");
      out.write("\t\tbuildCalendar(); //달력 cell 만들어 출력 \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction nextCalendar() {//다음 달\r\n");
      out.write("\t\t// 다음 달을 today에 값을 저장하고 달력에 today 넣어줌\r\n");
      out.write("\t\t//today.getFullYear() 현재 년도//today.getMonth() 월  //today.getDate() 일 \r\n");
      out.write("\t\t//getMonth()는 현재 달을 받아 오므로 다음달을 출력하려면 +1을 해줘야함\r\n");
      out.write("\t\ttoday = new Date(today.getFullYear(), today.getMonth() + 1, today\r\n");
      out.write("\t\t\t\t.getDate());\r\n");
      out.write("\t\tbuildCalendar();//달력 cell 만들어 출력\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction buildCalendar() {//현재 달 달력 만들기\r\n");
      out.write("\t\tvar doMonth = new Date(today.getFullYear(), today.getMonth(), 1);\r\n");
      out.write("\t\t//이번 달의 첫째 날,\r\n");
      out.write("\t\t//new를 쓰는 이유 : new를 쓰면 이번달의 로컬 월을 정확하게 받아온다.     \r\n");
      out.write("\t\t//new를 쓰지 않았을때 이번달을 받아오려면 +1을 해줘야한다. \r\n");
      out.write("\t\t//왜냐면 getMonth()는 0~11을 반환하기 때문\r\n");
      out.write("\t\tvar lastDate = new Date(today.getFullYear(), today.getMonth() + 1, 0);\r\n");
      out.write("\t\t//이번 달의 마지막 날\r\n");
      out.write("\t\t//new를 써주면 정확한 월을 가져옴, getMonth()+1을 해주면 다음달로 넘어가는데\r\n");
      out.write("\t\t//day를 1부터 시작하는게 아니라 0부터 시작하기 때문에 \r\n");
      out.write("\t\t//대로 된 다음달 시작일(1일)은 못가져오고 1 전인 0, 즉 전달 마지막일 을 가져오게 된다\r\n");
      out.write("\t\tvar tbCalendar = document.getElementById(\"calendar\");\r\n");
      out.write("\t\t//날짜를 찍을 테이블 변수 만듬, 일 까지 다 찍힘\r\n");
      out.write("\t\tvar tbCalendarYM = document.getElementById(\"tbCalendarYM\");\r\n");
      out.write("\t\t//테이블에 정확한 날짜 찍는 변수\r\n");
      out.write("\t\t//innerHTML : js 언어를 HTML의 권장 표준 언어로 바꾼다\r\n");
      out.write("\t\t//new를 찍지 않아서 month는 +1을 더해줘야 한다. \r\n");
      out.write("\t\ttbCalendarYM.innerHTML = today.getFullYear() + \"년 \"\r\n");
      out.write("\t\t\t\t+ (today.getMonth() + 1) + \"월\";\r\n");
      out.write("\r\n");
      out.write("\t\t/*while은 이번달이 끝나면 다음달로 넘겨주는 역할*/\r\n");
      out.write("\t\twhile (tbCalendar.rows.length > 2) {\r\n");
      out.write("\t\t\t//열을 지워줌\r\n");
      out.write("\t\t\t//기본 열 크기는 body 부분에서 2로 고정되어 있다.\r\n");
      out.write("\t\t\ttbCalendar.deleteRow(tbCalendar.rows.length - 1);\r\n");
      out.write("\t\t\t//테이블의 tr 갯수 만큼의 열 묶음은 -1칸 해줘야지 \r\n");
      out.write("\t\t\t//30일 이후로 담을달에 순서대로 열이 계속 이어진다.\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = null;\r\n");
      out.write("\t\trow = tbCalendar.insertRow();\r\n");
      out.write("\t\t//테이블에 새로운 열 삽입//즉, 초기화\r\n");
      out.write("\t\tvar cnt = 0;// count, 셀의 갯수를 세어주는 역할\r\n");
      out.write("\t\t// 1일이 시작되는 칸을 맞추어 줌\r\n");
      out.write("\t\tfor (i = 0; i < doMonth.getDay(); i++) {\r\n");
      out.write("\t\t\t/*이번달의 day만큼 돌림*/\r\n");
      out.write("\t\t\tcell = row.insertCell();//열 한칸한칸 계속 만들어주는 역할\r\n");
      out.write("\t\t\tcnt = cnt + 1;//열의 갯수를 계속 다음으로 위치하게 해주는 역할\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*달력 출력*/\r\n");
      out.write("\t\tfor (i = 1; i <= lastDate.getDate(); i++) {\r\n");
      out.write("\t\t\t//1일부터 마지막 일까지 돌림\r\n");
      out.write("\t\t\tcell = row.insertCell();//열 한칸한칸 계속 만들어주는 역할\r\n");
      out.write("\t\t\tcell.innerHTML = \"<input type='button' id=date\"+i+\" value=\"+i+\"  onclick='kkk(\"+i+\")' class='button' style='color:white;'>\"//셀을 1부터 마지막 day까지 HTML 문법에 넣어줌\r\n");
      out.write("\r\n");
      out.write("\t\t\tcnt = cnt + 1;//열의 갯수를 계속 다음으로 위치하게 해주는 역할\r\n");
      out.write("\t\t\tif (cnt % 7 == 1) {/*일요일 계산*/\r\n");
      out.write("\t\t\t\t//1주일이 7일 이므로 일요일 구하기\r\n");
      out.write("\t\t\t\t//월화수목금토일을 7로 나눴을때 나머지가 1이면 cnt가 1번째에 위치함을 의미한다\r\n");
      out.write("\t\t\t\tcell.innerHTML = \"<input type='button' id=date\"+i+\" value=\"+i+\"  onclick='kkk(\"+i+\")' class='button'>\"//셀을 1부터 마지막 day까지 HTML 문법에 넣어줌\r\n");
      out.write("\t\t\t\tcell.innerHTML = \"<font color=#F79DC2>\" + i\r\n");
      out.write("\t\t\t\t//1번째의 cell에만 색칠\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (cnt % 7 == 0) {/* 1주일이 7일 이므로 토요일 구하기*/\r\n");
      out.write("\t\t\t\t//월화수목금토일을 7로 나눴을때 나머지가 0이면 cnt가 7번째에 위치함을 의미한다\r\n");
      out.write("\t\t\t\tcell.innerHTML = \"<input type='button' id=date\"+i+\" value=\"+i+\"  onclick='kkk(\"+i+\")' class='button' font color=skyblue>\"//셀을 1부터 마지막 day까지 HTML 문법에 넣어줌\r\n");
      out.write("\t\t\t\tcell.innerHTML = \"<font color=skyblue>\" + i\r\n");
      out.write("\t\t\t\t//7번째의 cell에만 색칠\r\n");
      out.write("\t\t\t\trow = calendar.insertRow();\r\n");
      out.write("\t\t\t\t//토요일 다음에 올 셀을 추가\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/*오늘의 날짜에 노란색 칠하기*/\r\n");
      out.write("\t\t\tif (today.getFullYear() == date.getFullYear()\r\n");
      out.write("\t\t\t\t\t&& today.getMonth() == date.getMonth()\r\n");
      out.write("\t\t\t\t\t&& i == date.getDate()) {\r\n");
      out.write("\t\t\t\t//달력에 있는 년,달과 내 컴퓨터의 로컬 년,달이 같고, 일이 오늘의 일과 같으면\r\n");
      out.write("\t\t\t\tcell.bgColor = \"#A43BE6\";//셀의 배경색을 노랑으로 \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   function kkk(vday) {\r\n");
      out.write("\t     var tRe_morning = document.getElementById('tRe_morning');\r\n");
      out.write("\t     var tRe_afternoon = document.getElementById('tRe_afternoon');\r\n");
      out.write("\t     var tRe_night = document.getElementById('tRe_night');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tvar toMon = today.getMonth()+1;\r\n");
      out.write("        var calDay = today.getFullYear()+\".\"+toMon+\".\"+vday;\r\n");
      out.write("        var vro_num =1;//나중에 파라미터로 전환\r\n");
      out.write(" \t    alert(\"vday->\"+vday);\r\n");
      out.write(" \t    alert(\"선택하신 예약일시:\"+calDay);\r\n");
      out.write("\t    $('#select_date').html(calDay);         /* span  id Tag */\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print(context);
      out.write("/resv/reservation.do\",\r\n");
      out.write("\t\t\tdata:{ro_num   : vro_num,\r\n");
      out.write("\t\t\t\t  re_rvdate : calDay\r\n");
      out.write("\t\t\t     },\r\n");
      out.write("\t\t\tdataType:'json',\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t/*  alert(\".ajax getDept Data\"+data);  */\r\n");
      out.write("\t\t\t\tstr   = data.re_morning + \" \" + data.re_afternoon + \" \" + data.re_night;\r\n");
      out.write("/* \t\t\t\t$('#RestDept1').val(str);       input Tag \r\n");
      out.write("\t\t\t\t$('#RestDept2').val(str);      input Tag  \r\n");
      out.write(" */\t\t\t\talert(\".ajax getDept str\"+str); \r\n");
      out.write("                $('#select_date').html(calDay);         /* span  id Tag */\r\n");
      out.write("\r\n");
      out.write("                if (data.re_morning == 0) {\r\n");
      out.write("        \t               tRe_morning.innerHTML = \"<li>아침<input type='radio' name='re_morning'     value='0'><br></li>\";\r\n");
      out.write(" \t\t\t    } else {\r\n");
      out.write(" \t       \t           tRe_morning.innerHTML = \"<li>아침</li>\";\r\n");
      out.write(" \t\t\t    }\r\n");
      out.write("                if (data.re_afternoon == 0) {\r\n");
      out.write("        \t               tRe_afternoon.innerHTML = \"<li>점심<input type='radio' name='re_afternoon'     value='0'><br></li>\";\r\n");
      out.write(" \t\t\t    } else {\r\n");
      out.write(" \t       \t           tRe_afternoon.innerHTML = \"<li>점심</li>\";\r\n");
      out.write(" \t\t\t    }\r\n");
      out.write("                if (data.re_night == 0) {\r\n");
      out.write("        \t               tRe_night.innerHTML = \"<li>저녁<input type='radio' name='re_night'     value='0'><br></li>\";\r\n");
      out.write(" \t\t\t    } else {\r\n");
      out.write(" \t       \t           tRe_night.innerHTML = \"<li>저녁</li>\";\r\n");
      out.write(" \t\t\t    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}  \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"mini-calendar\">\r\n");
      out.write("<table id=\"calendar\" border=\"3\" align=\"center\"\r\n");
      out.write("\t\tstyle=\"border-color: #020202\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<!-- label은 마우스로 클릭을 편하게 해줌 -->\r\n");
      out.write("\t\t\t<td><label onclick=\"prevCalendar()\">< </label></td>\r\n");
      out.write("\t\t\t<td align=\"center\" id=\"tbCalendarYM\" colspan=\"5\">yyyy년 m월</td>\r\n");
      out.write("\t\t\t<td><label onclick=\"nextCalendar()\">> </label></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"aa\">\r\n");
      out.write("\t\t\t<td align=\"center\" onclick=\"kkk(2)\"><font color=\"#F79DC2\">일</td>\r\n");
      out.write("\t\t\t<td align=\"center\">월</td>\r\n");
      out.write("\t\t\t<td align=\"center\">화</td>\r\n");
      out.write("\t\t\t<td align=\"center\">수</td>\r\n");
      out.write("\t\t\t<td align=\"center\">목</td>\r\n");
      out.write("\t\t\t<td align=\"center\">금</td>\r\n");
      out.write("\t\t\t<td align=\"center\"><font color=\"skyblue\">토</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\t<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\t\tbuildCalendar();//\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"reserve-container\">\r\n");
      out.write("\t\t<div class=\"studyroom-part\">\r\n");
      out.write("\t\t\t<div class=\"reserve-title\">스터디룸</div>\r\n");
      out.write("\t\t\t<div class=\"sort-wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"sort-rate sort-selected\">지역</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"studyroom-list\">\r\n");
      out.write("\t\t\t지역:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ro_loc }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"time-part\">\r\n");
      out.write("\t\t\t<div class=\"reserve-title\">시간</div>\r\n");
      out.write("\t\t\t<div class=\"css_test\">\r\n");
      out.write("\t\t\t\t<p>시간대 선택</p>\r\n");
      out.write("\t\t\t\t<form action=\"\"></form>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"morning\" name=\"morning\" value=\"morning\">\r\n");
      out.write("\t\t\t  <label for=\"morning\">아침</label><br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"afternoon\" name=\"afternoon\" value=\"afternoon\">\r\n");
      out.write("\t\t\t  <label for=\"afternoon\">오후</label><br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"night\" name=\"night\" value=\"night\">\r\n");
      out.write("\t\t\t  <label for=\"night\">저녁</label><br><br>\r\n");
      out.write("\t\t\t\t<input class=\"time_submit\" type=\"submit\" value=\"선택완료\" onclick=\"time_submit\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
