/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2020-06-03 03:11:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.room;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/room/header.jsp", Long.valueOf(1591153599636L));
    _jspx_dependants.put("jar:file:/C:/spring/springSrc39/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/s20200502k/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1587711624888L));
    _jspx_dependants.put("jar:file:/C:/spring/springSrc39/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/s20200502k/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write(".form-inline .form-control {\r\n");
      out.write("width: 40vw;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar fixed-top navbar-expand-lg bg-light navbar-light\">\r\n");
      out.write("\t\t<a class=\"navebar-brand\" href=\"main\"><img class=\"logoimg\" alt=\"brand\" src=\"resources/Image/harang5.png\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav mr-auto ml-auto\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<form class=\"form-inline\" action=\"listSearch\" method=\"GET\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"검색어\">\r\n");
      out.write("\t\t\t\t\t<input class=\"btn btn-primary\" type=\"submit\" value=\"검색\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t\t<!-- 메인 메뉴 -->\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav navbar-dark\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" data-toggle=\"dropdown\">메뉴</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"loginForm\">로그인/회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"roomList\">방 검색</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"boardList\">공지사항&스터디그룹</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Q&A</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"myInfo\">마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"roomInsertGo\">방등록하기(사업자)</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"levelList\">방승인(사업자)</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>main</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write("  /* Make the image fully responsive */\r\n");
      out.write("  .carousel-inner img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("  }\r\n");
      out.write("  .text-center{\r\n");
      out.write("font-family: 'Hi Melody', cursive;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hi+Melody&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 메인 배너(캐러셀) -->\r\n");
      out.write("<div id=\"demo\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("  <ul class=\"carousel-indicators\">\r\n");
      out.write("    <li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("    <li data-target=\"#demo\" data-slide-to=\"1\"></li>\r\n");
      out.write("    <li data-target=\"#demo\" data-slide-to=\"2\"></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img src=\"resources/Image/7-2.jpg\" alt=\"Place\" width=\"1100\" height=\"500\">\r\n");
      out.write("      <div class=\"carousel-caption\">\r\n");
      out.write("        <h3>공부할 장소가 필요하신가요???</h3>\r\n");
      out.write("        <p>공부하랑에서 당신이 필요한 곳을 찾으세요!</p>\r\n");
      out.write("      </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"resources/Image/7-3.jpg\" alt=\"Concentration\" width=\"1100\" height=\"500\">\r\n");
      out.write("      <div class=\"carousel-caption\">\r\n");
      out.write("        <h3>집중이 안되시나요?</h3>\r\n");
      out.write("        <p>공부하랑에서 집중력을 높이는 곳을 찾으세요!</p>\r\n");
      out.write("      </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"resources/Image/7-1.jpg\" alt=\"MeetUP!\" width=\"1100\" height=\"500\">\r\n");
      out.write("      <div class=\"carousel-caption\">\r\n");
      out.write("        <h3>모임 장소가 필요하세요?</h3>\r\n");
      out.write("        <p>공부하랑에서 다양한 장소를 알아보세요!</p>\r\n");
      out.write("      </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <a class=\"carousel-control-prev\" href=\"#demo\" data-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a class=\"carousel-control-next\" href=\"#demo\" data-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("  </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 지역구 나누기 -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h1 class=\"text-center\">어느 지역에서 찾으시나요?</h1>  \r\n");
      out.write("\t<div class=\"table-responsive\">\r\n");
      out.write("\t  <table class=\"table\">\r\n");
      out.write("\t      <tbody>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t\t<td class=\"text-center\"><a href=\"list.do\"> 강남구</a></td>\r\n");
      out.write("\t\t<td class=\"text-center\">강동구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">강북구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">강서구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">관악구</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t\t<td class=\"text-center\">광진구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">구로구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">금천구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">노원구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">도봉구</td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t\t<td class=\"text-center\">동대문구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">동작구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">마포구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">서대문구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">서초구</td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t <tr>\r\n");
      out.write("\t\t<td class=\"text-center\">성동구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">성북구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">송파구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">양천구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">영등포구</td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t <tr>\r\n");
      out.write("\t\t<td class=\"text-center\">용산구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">은평구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">종로구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">중구</td>\r\n");
      out.write("\t\t<td class=\"text-center\">중랑구</td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t    </tbody>\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 금주의 인기방 -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1 class=\"text-center\">금주 인기방</h1>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"thumbnail\"> <img src=\"resources/Image/1.jpg\" alt=\"...\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"thumbnail\"> <img src=\"resources/Image/2.jpg\" alt=\"...\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"thumbnail\"> <img src=\"resources/Image/3.jpg\" alt=\"...\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"thumbnail\"> <img src=\"resources/Image/4.jpg\" alt=\"...\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-6 col-md-3 \">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/Image/1.jpg\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t<h3>제목과</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>내용도 넣을 수 있다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Button</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/Image/2.jpg\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t<h3>제목과</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>내용도 넣을 수 있다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Button</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/Image/3.jpg\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t<h3>제목과</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>내용도 넣을 수 있다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Button</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/Image/4.jpg\" alt=\"...\">\r\n");
      out.write("\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t<h3>제목과</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>내용도 넣을 수 있다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-default\" role=\"button\">Button</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- container 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
